# .github/workflows/pacman.yml
name: GitHub Pac-Man Game

on:
  # Daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Manual trigger
  workflow_dispatch:
  # On pushes to main
  push:
    branches:
      - main

jobs:
  generate:
    # Allows pushing to the output branch
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          # Uses your profile repo owner by default
          github_user_name: ${{ github.repository_owner }} :contentReference[oaicite:0]{index=0}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update pac-man graph [skip ci]" :contentReference[oaicite:1]{index=1}
